### ISSUE TITLE
Lumpy fails, Alignment stuck in variant calling

### ISSUE THREAD

**Issue by woodymit** [churchlab/millstone#584]
trace:
http://pastebin.com/VNvBDyvN

**Comment by glebkuznetsov** [comment]
We figured out this was due to lumpyexpress passing the tail of the bam file to pairend_distro.py. And the tail is where unmapped reads lie. This particular sample apparently had enough unmapped reads to make this a problem for calculating the pairend distribution.

@woodymit fixed this here:
https://github.com/churchlab/lumpy-sv/commit/1716e4be05c5b9f5bd9825d17ea0221da0a46b15

However, this requires perl and would be nice if it didn't. I doubt the lumpy guys will accept a pull request with this fix.

I've updated the lumpy zips in the Dropbox binary distribution with this fixed script.
