### ISSUE TITLE
Parallelize contig assembly on multiple samples

### ISSUE THREAD

**Issue by glebkuznetsov** [churchlab/millstone#627]
(Not urgent, but an easy optimization)

Right now this creates a single celery task which runs the assemblies in series:
https://github.com/churchlab/millstone/blob/d75ca087fa8cf51c34622d1648961f89ede9c36b/genome_designer/genome_finish/assembly.py#L73

Should be a matter of just kicking off a separate celery task for each.

Is there any concurrency issue that might arise here?

**Comment by woodymit** [comment]
Originally I implemented it so that it kicked off a separate celery task for each, but there were concurrency issues.  I believe the issue was two threads could make the same variant at the same time.  I tried using existing atomicity features of the django database wrapper, but I couldn't get it to work.  I'll try again, because this would obviously speed up SV discovery quite a bit.
