### ISSUE TITLE
Dataset.filesystem_idx_location used inconsistently

### ISSUE THREAD

**Issue by woodymit** [churchlab/millstone#631]
This method of the Dataset model uses the filesystem_idx_location to check if the Dataset has an associated index file: https://github.com/churchlab/millstone/blob/3c643a23c205ca244f0798d8434f2cb775f6d990/genome_designer/main/models.py#L249

But in the read alignment pipeline the reference is indexed using pipeline.read_alignment_util.ensure_bwa_index: https://github.com/churchlab/millstone/blob/3c643a23c205ca244f0798d8434f2cb775f6d990/genome_designer/pipeline/read_alignment_util.py#L23

**Comment by glebkuznetsov** [comment]
Good catch Brian. Needs to be fixed everywhere, or remove this function from Dataset. I recommend the latter :)

**Comment by dbgoodman** [comment]
I will take a look, but my memory is that there are other indices besides the bwa ban index, and this is the  issue.

**Comment by glebkuznetsov** [comment]
It was a good idea, but unfortunately not used consistently. The only place that uses it is:
https://github.com/churchlab/millstone/blob/3c643a23c205ca244f0798d8434f2cb775f6d990/genome_designer/utils/jbrowse_util.py#L364

Since it's not a high priority, it's better to fix it by removing the global thing and having a custom function just for jbrowse. As opposed to make sure you fixed this everywhere.
